// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PhoneInfo.proto
// Protobuf Java Version: 4.29.2

package org.hadoop.learn.phone.log.proto;

public interface PhoneInfoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:org.hadoop.learn.phone.log.PhoneInfo)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string snum = 1;</code>
     *
     * @return Whether the snum field is set.
     */
    boolean hasSnum();

    /**
     * <code>required string snum = 1;</code>
     *
     * @return The snum.
     */
    java.lang.String getSnum();

    /**
     * <code>required string snum = 1;</code>
     *
     * @return The bytes for snum.
     */
    com.google.protobuf.ByteString
    getSnumBytes();

    /**
     * <code>required string rnum = 2;</code>
     *
     * @return Whether the rnum field is set.
     */
    boolean hasRnum();

    /**
     * <code>required string rnum = 2;</code>
     *
     * @return The rnum.
     */
    java.lang.String getRnum();

    /**
     * <code>required string rnum = 2;</code>
     *
     * @return The bytes for rnum.
     */
    com.google.protobuf.ByteString
    getRnumBytes();

    /**
     * <code>required int64 seconds = 3;</code>
     *
     * @return Whether the seconds field is set.
     */
    boolean hasSeconds();

    /**
     * <code>required int64 seconds = 3;</code>
     *
     * @return The seconds.
     */
    long getSeconds();

    /**
     * <code>required string datetime = 4;</code>
     *
     * @return Whether the datetime field is set.
     */
    boolean hasDatetime();

    /**
     * <code>required string datetime = 4;</code>
     *
     * @return The datetime.
     */
    java.lang.String getDatetime();

    /**
     * <code>required string datetime = 4;</code>
     *
     * @return The bytes for datetime.
     */
    com.google.protobuf.ByteString
    getDatetimeBytes();
}
