// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PhoneInfo.proto
// Protobuf Java Version: 4.29.2

package org.hadoop.learn.phone.log.proto;

public final class PhoneInfoProto {
    private PhoneInfoProto() {
    }

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 29,
                /* patch= */ 2,
                /* suffix= */ "",
                PhoneInfoProto.class.getName());
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_org_hadoop_learn_phone_log_PhoneInfo_descriptor;
    static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_org_hadoop_learn_phone_log_PhoneInfo_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\017PhoneInfo.proto\022\032org.hadoop.learn.phon" +
                        "e.log\"J\n\tPhoneInfo\022\014\n\004snum\030\001 \002(\t\022\014\n\004rnum" +
                        "\030\002 \002(\t\022\017\n\007seconds\030\003 \002(\003\022\020\n\010datetime\030\004 \002(" +
                        "\tB1\n\032org.hadoop.learn.phone.logB\016PhoneIn" +
                        "foProtoP\001\240\001\001"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_org_hadoop_learn_phone_log_PhoneInfo_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_org_hadoop_learn_phone_log_PhoneInfo_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_org_hadoop_learn_phone_log_PhoneInfo_descriptor,
                new java.lang.String[]{"Snum", "Rnum", "Seconds", "Datetime",});
        descriptor.resolveAllFeaturesImmutable();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
