// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PhoneInfo.proto
// Protobuf Java Version: 4.29.2

package org.hadoop.learn.phone.log.proto;

/**
 * <pre>
 * *
 * 定义手机通话信息
 * </pre>
 * <p>
 * Protobuf type {@code org.hadoop.learn.phone.log.PhoneInfo}
 */
public final class PhoneInfo extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:org.hadoop.learn.phone.log.PhoneInfo)
        PhoneInfoOrBuilder {
    private static final long serialVersionUID = 0L;

//    static {
//        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
//                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
//                /* major= */ 4,
//                /* minor= */ 29,
//                /* patch= */ 2,
//                /* suffix= */ "",
//                PhoneInfo.class.getName());
//    }

    // Use PhoneInfo.newBuilder() to construct.
    private PhoneInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
    }

    private PhoneInfo() {
        snum_ = "";
        rnum_ = "";
        datetime_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return PhoneInfoProto.internal_static_org_hadoop_learn_phone_log_PhoneInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return PhoneInfoProto.internal_static_org_hadoop_learn_phone_log_PhoneInfo_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        PhoneInfo.class, PhoneInfo.Builder.class);
    }

    private int bitField0_;
    public static final int SNUM_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object snum_ = "";

    /**
     * <code>required string snum = 1;</code>
     *
     * @return Whether the snum field is set.
     */
    @java.lang.Override
    public boolean hasSnum() {
        return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>required string snum = 1;</code>
     *
     * @return The snum.
     */
    @java.lang.Override
    public java.lang.String getSnum() {
        java.lang.Object ref = snum_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
                snum_ = s;
            }
            return s;
        }
    }

    /**
     * <code>required string snum = 1;</code>
     *
     * @return The bytes for snum.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getSnumBytes() {
        java.lang.Object ref = snum_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            snum_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int RNUM_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object rnum_ = "";

    /**
     * <code>required string rnum = 2;</code>
     *
     * @return Whether the rnum field is set.
     */
    @java.lang.Override
    public boolean hasRnum() {
        return ((bitField0_ & 0x00000002) != 0);
    }

    /**
     * <code>required string rnum = 2;</code>
     *
     * @return The rnum.
     */
    @java.lang.Override
    public java.lang.String getRnum() {
        java.lang.Object ref = rnum_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
                rnum_ = s;
            }
            return s;
        }
    }

    /**
     * <code>required string rnum = 2;</code>
     *
     * @return The bytes for rnum.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getRnumBytes() {
        java.lang.Object ref = rnum_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            rnum_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int SECONDS_FIELD_NUMBER = 3;
    private long seconds_ = 0L;

    /**
     * <code>required int64 seconds = 3;</code>
     *
     * @return Whether the seconds field is set.
     */
    @java.lang.Override
    public boolean hasSeconds() {
        return ((bitField0_ & 0x00000004) != 0);
    }

    /**
     * <code>required int64 seconds = 3;</code>
     *
     * @return The seconds.
     */
    @java.lang.Override
    public long getSeconds() {
        return seconds_;
    }

    public static final int DATETIME_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object datetime_ = "";

    /**
     * <code>required string datetime = 4;</code>
     *
     * @return Whether the datetime field is set.
     */
    @java.lang.Override
    public boolean hasDatetime() {
        return ((bitField0_ & 0x00000008) != 0);
    }

    /**
     * <code>required string datetime = 4;</code>
     *
     * @return The datetime.
     */
    @java.lang.Override
    public java.lang.String getDatetime() {
        java.lang.Object ref = datetime_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
                datetime_ = s;
            }
            return s;
        }
    }

    /**
     * <code>required string datetime = 4;</code>
     *
     * @return The bytes for datetime.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getDatetimeBytes() {
        java.lang.Object ref = datetime_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            datetime_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasSnum()) {
            memoizedIsInitialized = 0;
            return false;
        }
        if (!hasRnum()) {
            memoizedIsInitialized = 0;
            return false;
        }
        if (!hasSeconds()) {
            memoizedIsInitialized = 0;
            return false;
        }
        if (!hasDatetime()) {
            memoizedIsInitialized = 0;
            return false;
        }
        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 1, snum_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 2, rnum_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
            output.writeInt64(3, seconds_);
        }
        if (((bitField0_ & 0x00000008) != 0)) {
            com.google.protobuf.GeneratedMessage.writeString(output, 4, datetime_);
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(1, snum_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(2, rnum_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(3, seconds_);
        }
        if (((bitField0_ & 0x00000008) != 0)) {
            size += com.google.protobuf.GeneratedMessage.computeStringSize(4, datetime_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof PhoneInfo)) {
            return super.equals(obj);
        }
        PhoneInfo other = (PhoneInfo) obj;

        if (hasSnum() != other.hasSnum()) return false;
        if (hasSnum()) {
            if (!getSnum()
                    .equals(other.getSnum())) return false;
        }
        if (hasRnum() != other.hasRnum()) return false;
        if (hasRnum()) {
            if (!getRnum()
                    .equals(other.getRnum())) return false;
        }
        if (hasSeconds() != other.hasSeconds()) return false;
        if (hasSeconds()) {
            if (getSeconds()
                    != other.getSeconds()) return false;
        }
        if (hasDatetime() != other.hasDatetime()) return false;
        if (hasDatetime()) {
            if (!getDatetime()
                    .equals(other.getDatetime())) return false;
        }
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasSnum()) {
            hash = (37 * hash) + SNUM_FIELD_NUMBER;
            hash = (53 * hash) + getSnum().hashCode();
        }
        if (hasRnum()) {
            hash = (37 * hash) + RNUM_FIELD_NUMBER;
            hash = (53 * hash) + getRnum().hashCode();
        }
        if (hasSeconds()) {
            hash = (37 * hash) + SECONDS_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getSeconds());
        }
        if (hasDatetime()) {
            hash = (37 * hash) + DATETIME_FIELD_NUMBER;
            hash = (53 * hash) + getDatetime().hashCode();
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static PhoneInfo parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static PhoneInfo parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static PhoneInfo parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static PhoneInfo parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static PhoneInfo parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static PhoneInfo parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static PhoneInfo parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input);
    }

    public static PhoneInfo parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static PhoneInfo parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static PhoneInfo parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static PhoneInfo parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input);
    }

    public static PhoneInfo parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(PhoneInfo prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * <pre>
     * *
     * 定义手机通话信息
     * </pre>
     * <p>
     * Protobuf type {@code org.hadoop.learn.phone.log.PhoneInfo}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:org.hadoop.learn.phone.log.PhoneInfo)
            PhoneInfoOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return PhoneInfoProto.internal_static_org_hadoop_learn_phone_log_PhoneInfo_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return PhoneInfoProto.internal_static_org_hadoop_learn_phone_log_PhoneInfo_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            PhoneInfo.class, PhoneInfo.Builder.class);
        }

        // Construct using org.hadoop.learn.phone.log.PhoneInfo.newBuilder()
        private Builder() {

        }

        private Builder(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            super(parent);

        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            snum_ = "";
            rnum_ = "";
            seconds_ = 0L;
            datetime_ = "";
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return PhoneInfoProto.internal_static_org_hadoop_learn_phone_log_PhoneInfo_descriptor;
        }

        @java.lang.Override
        public PhoneInfo getDefaultInstanceForType() {
            return PhoneInfo.getDefaultInstance();
        }

        @java.lang.Override
        public PhoneInfo build() {
            PhoneInfo result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public PhoneInfo buildPartial() {
            PhoneInfo result = new PhoneInfo(this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(PhoneInfo result) {
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.snum_ = snum_;
                to_bitField0_ |= 0x00000001;
            }
            if (((from_bitField0_ & 0x00000002) != 0)) {
                result.rnum_ = rnum_;
                to_bitField0_ |= 0x00000002;
            }
            if (((from_bitField0_ & 0x00000004) != 0)) {
                result.seconds_ = seconds_;
                to_bitField0_ |= 0x00000004;
            }
            if (((from_bitField0_ & 0x00000008) != 0)) {
                result.datetime_ = datetime_;
                to_bitField0_ |= 0x00000008;
            }
            result.bitField0_ |= to_bitField0_;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof PhoneInfo) {
                return mergeFrom((PhoneInfo) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(PhoneInfo other) {
            if (other == PhoneInfo.getDefaultInstance()) return this;
            if (other.hasSnum()) {
                snum_ = other.snum_;
                bitField0_ |= 0x00000001;
                onChanged();
            }
            if (other.hasRnum()) {
                rnum_ = other.rnum_;
                bitField0_ |= 0x00000002;
                onChanged();
            }
            if (other.hasSeconds()) {
                setSeconds(other.getSeconds());
            }
            if (other.hasDatetime()) {
                datetime_ = other.datetime_;
                bitField0_ |= 0x00000008;
                onChanged();
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            if (!hasSnum()) {
                return false;
            }
            if (!hasRnum()) {
                return false;
            }
            if (!hasSeconds()) {
                return false;
            }
            if (!hasDatetime()) {
                return false;
            }
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            snum_ = input.readBytes();
                            bitField0_ |= 0x00000001;
                            break;
                        } // case 10
                        case 18: {
                            rnum_ = input.readBytes();
                            bitField0_ |= 0x00000002;
                            break;
                        } // case 18
                        case 24: {
                            seconds_ = input.readInt64();
                            bitField0_ |= 0x00000004;
                            break;
                        } // case 24
                        case 34: {
                            datetime_ = input.readBytes();
                            bitField0_ |= 0x00000008;
                            break;
                        } // case 34
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        private int bitField0_;

        private java.lang.Object snum_ = "";

        /**
         * <code>required string snum = 1;</code>
         *
         * @return Whether the snum field is set.
         */
        public boolean hasSnum() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>required string snum = 1;</code>
         *
         * @return The snum.
         */
        public java.lang.String getSnum() {
            java.lang.Object ref = snum_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    snum_ = s;
                }
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>required string snum = 1;</code>
         *
         * @return The bytes for snum.
         */
        public com.google.protobuf.ByteString
        getSnumBytes() {
            java.lang.Object ref = snum_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                snum_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>required string snum = 1;</code>
         *
         * @param value The snum to set.
         * @return This builder for chaining.
         */
        public Builder setSnum(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            snum_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <code>required string snum = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearSnum() {
            snum_ = getDefaultInstance().getSnum();
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
            return this;
        }

        /**
         * <code>required string snum = 1;</code>
         *
         * @param value The bytes for snum to set.
         * @return This builder for chaining.
         */
        public Builder setSnumBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            snum_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        private java.lang.Object rnum_ = "";

        /**
         * <code>required string rnum = 2;</code>
         *
         * @return Whether the rnum field is set.
         */
        public boolean hasRnum() {
            return ((bitField0_ & 0x00000002) != 0);
        }

        /**
         * <code>required string rnum = 2;</code>
         *
         * @return The rnum.
         */
        public java.lang.String getRnum() {
            java.lang.Object ref = rnum_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    rnum_ = s;
                }
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>required string rnum = 2;</code>
         *
         * @return The bytes for rnum.
         */
        public com.google.protobuf.ByteString
        getRnumBytes() {
            java.lang.Object ref = rnum_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                rnum_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>required string rnum = 2;</code>
         *
         * @param value The rnum to set.
         * @return This builder for chaining.
         */
        public Builder setRnum(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            rnum_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        /**
         * <code>required string rnum = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearRnum() {
            rnum_ = getDefaultInstance().getRnum();
            bitField0_ = (bitField0_ & ~0x00000002);
            onChanged();
            return this;
        }

        /**
         * <code>required string rnum = 2;</code>
         *
         * @param value The bytes for rnum to set.
         * @return This builder for chaining.
         */
        public Builder setRnumBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            rnum_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        private long seconds_;

        /**
         * <code>required int64 seconds = 3;</code>
         *
         * @return Whether the seconds field is set.
         */
        @java.lang.Override
        public boolean hasSeconds() {
            return ((bitField0_ & 0x00000004) != 0);
        }

        /**
         * <code>required int64 seconds = 3;</code>
         *
         * @return The seconds.
         */
        @java.lang.Override
        public long getSeconds() {
            return seconds_;
        }

        /**
         * <code>required int64 seconds = 3;</code>
         *
         * @param value The seconds to set.
         * @return This builder for chaining.
         */
        public Builder setSeconds(long value) {

            seconds_ = value;
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        /**
         * <code>required int64 seconds = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearSeconds() {
            bitField0_ = (bitField0_ & ~0x00000004);
            seconds_ = 0L;
            onChanged();
            return this;
        }

        private java.lang.Object datetime_ = "";

        /**
         * <code>required string datetime = 4;</code>
         *
         * @return Whether the datetime field is set.
         */
        public boolean hasDatetime() {
            return ((bitField0_ & 0x00000008) != 0);
        }

        /**
         * <code>required string datetime = 4;</code>
         *
         * @return The datetime.
         */
        public java.lang.String getDatetime() {
            java.lang.Object ref = datetime_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    datetime_ = s;
                }
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>required string datetime = 4;</code>
         *
         * @return The bytes for datetime.
         */
        public com.google.protobuf.ByteString
        getDatetimeBytes() {
            java.lang.Object ref = datetime_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                datetime_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>required string datetime = 4;</code>
         *
         * @param value The datetime to set.
         * @return This builder for chaining.
         */
        public Builder setDatetime(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            datetime_ = value;
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }

        /**
         * <code>required string datetime = 4;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearDatetime() {
            datetime_ = getDefaultInstance().getDatetime();
            bitField0_ = (bitField0_ & ~0x00000008);
            onChanged();
            return this;
        }

        /**
         * <code>required string datetime = 4;</code>
         *
         * @param value The bytes for datetime to set.
         * @return This builder for chaining.
         */
        public Builder setDatetimeBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            datetime_ = value;
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }

        // @@protoc_insertion_point(builder_scope:org.hadoop.learn.phone.log.PhoneInfo)
    }

    // @@protoc_insertion_point(class_scope:org.hadoop.learn.phone.log.PhoneInfo)
    private static final PhoneInfo DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new PhoneInfo();
    }

    public static PhoneInfo getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PhoneInfo>
            PARSER = new com.google.protobuf.AbstractParser<PhoneInfo>() {
        @java.lang.Override
        public PhoneInfo parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e)
                        .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<PhoneInfo> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PhoneInfo> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public PhoneInfo getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

